=== axelgarcia1A/pt3_garcia_axel_singh_taranpreet.github.io/XSLT/recetas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="receptes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="recepta" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="autor" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nom_persona" type="xs:string"/>
                                        <xs:element name="dni">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="\d{8}[A-Za-z]"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="nom_recepta" type="xs:string"/>
                            <xs:element name="ingredients" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ingredient" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="quantitat">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="valor" type="xs:string"/>
                                                                <xs:element name="mesura" type="xs:string"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="nom" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="imatge" type="xs:string" />
                            <xs:element name="descripcio" type="xs:string" />
                            <xs:element name="passos">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="pas" type="xs:string" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== axelgarcia1A/pt3_garcia_axel_singh_taranpreet.github.io/XSLT/recetas.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="recetas.xsl"?>
<receptes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="recetas.xsd">
    <recepta>
        <autor>
            <nom_persona>Chef Pastoso</nom_persona>
            <dni>81932732S</dni>
        </autor>
        <nom_recepta>Pasta con salsa de coliflor y pimienta de Jamaica</nom_recepta>
        <ingredients>
            <ingredient>
                <quantitat>
                    <valor>4</valor>
                    <mesura>cucharadas</mesura>
                </quantitat>
                <nom>Aceite de oliva virgen extra</nom>
            </ingredient>
            <ingredient>
                <quantitat>
                    <valor>1</valor>
                    <mesura>unidad</mesura>
                </quantitat>
                <nom>Cebolla hermosa</nom>
            </ingredient>
            <ingredient>
                <quantitat>
                    <valor>500</valor>
                    <mesura>gramos</mesura>
                </quantitat>
                <nom>Coliflor</nom>
            </ingredient>
            <ingredient>
                <quantitat>
                    <valor>2</valor>
                    <mesura>tazas</mesura>
                </quantitat>
                <nom>Caldo vegetal</nom>
            </ingredient>
            <ingredient>
                <quantitat>
                    <valor>2</valor>
                    <mesura>cucharadas</mesura>
                </quantitat>
                <nom>Levadura nutricional</nom>
            </ingredient>
            <ingredient>
                <quantitat>
                    <valor>0.5</valor>
                    <mesura>taza</mesura>
                </quantitat>
                <nom>Leche de almendras</nom>
            </ingredient>
            <ingredient>
                <quantitat>
                    <valor>1</valor>
                    <mesura>cucharada</mesura>
                </quantitat>
                <nom>Sal</nom>
            </ingredient>
        </ingredients>
        <imatge>https://r2.fivemanage.com/pub/u98psdb6e4n6.jpg</imatge>
        <descripcio>Una salsa vegana para la pasta, tan sobrosa y cremosa que resulta irresistible! Está elaborada con coliflor y con otros ingredientes vegetales, que la convierten en un plato ideal.</descripcio>
        <passos>
            <pas>Preparar la cebolla: Picaremos bien fina la cebolla y la sofreiremos en el aceite hasta que esté translucida.</pas>
            <pas>Añadir los ajos: Añadiremos entonces los ajos prensados o picados finos.</pas>
            <pas>Incluir la coliflor: Incorporaremos la coliflor troceada o separada en flores, el caldo y dejaremos cocer hasta que esté tierna, seguramente se consumirá gran parte del líquido.</pas>
            <pas>Añadir el resto de ingredientes: Echaremos la preparación en el vaso de la batidora y añadiremos la leche, la levadura, los granos de pimienta y un poco de sal al gusto. Batiremos hasta conseguir una textura fina.</pas>
            <pas>Servir: Una vez esté bien batida, utilizaremos esta salsa para acompañar cualquier plato de pasta.</pas>
        </passos>
    </recepta>
    <recepta>
        <autor>
            <nom_persona>Chef Galletas</nom_persona>
            <dni>81927287G</dni>
        </autor>
        <nom_recepta>Galletas de avena, rosa y lima</nom_recepta>
        <ingredients>
            <ingredient>
                <quantitat>
                    <valor>3/4</valor>
                    <mesura>taza</mesura>
                </quantitat>
                <nom>Harina de avena (80g)</nom>
            </ingredient>
            <ingredient>
                <quantitat>
                    <valor>1/4</valor>
                    <mesura>taza</mesura>
                </quantitat>
                <nom>Azúcar</nom>
            </ingredient>
            <ingredient>
                <quantitat>
                    <valor>0.5</valor>
                    <mesura>cucharada</mesura>
                </quantitat>
                <nom>Semillas de lino triturado</nom>
            </ingredient>
            <ingredient>
                <quantitat>
                    <valor>2</valor>
                    <mesura>cucharadas</mesura>
                </quantitat>
                <nom>Agua</nom>
            </ingredient>
            <ingredient>
                <quantitat>
                    <valor>4</valor>
                    <mesura>gotas</mesura>
                </quantitat>
                <nom>Esencia de rosa</nom>
            </ingredient>
            <ingredient>
                <quantitat>
                    <valor>0.5</valor>
                    <mesura>unidad</mesura>
                </quantitat>
                <nom>Lima rallada (solo la piel)</nom>
            </ingredient>
            <ingredient>
                <quantitat>
                    <valor>0.5</valor>
                    <mesura>g</mesura>
                </quantitat>
                <nom>Ágave en polvo edulzante en polvo blanco para decorar (opcional)</nom>
            </ingredient>
        </ingredients>
        <imatge>https://r2.fivemanage.com/pub/c36ji0c80fbx.jpg</imatge>
        <descripcio>
            Galletitas para San Valentín? Estas galletas ricas y crujientes, elaboradas con avena y con rico sabor a rosa y lima son perfectas para celebrarlo!
        </descripcio>
        <passos>
            <pas>
                Masa: Echaremos todos los ingredientes de la masa de galletas en un bol y amasaremos un poco para que se mezcle todo bien. Dejaremos enfriar un rato en la nevera o unos minutos en el congelador para manipularla mejor y más cómodamente, aunque puede no ser necesario.
            </pas>
            <pas>
                Estirar masa: Estiraremos la masa con un rodillo a un grosor de medio cm y con un cortapastas les haremos la forma, utilizando uno más pequeño para quitar el centro de la mitad de ellas. En el horno previamente caliente, hornearemos a 180ºC hasta que empiecen a estar doradas, más o menos unos 12 minutos, aunque cada horno es diferente y hay que estar al tanto para que no se nos quemen.
            </pas>
            <pas>
                Enfriar: Las sacaremos y las dejaremos enfriar en una rejilla para que queden crujientes. Cuando estén frías, las espolvorearemos con un poco de ágave en polvo, para darle un bonito toque nevadito.
            </pas>
            <pas>
                Mermelada: Para hacer la mermelada, echaremos todos los ingredientes en una olla pequeña, a fuego medio llevaremos a ebullición, bajaremos el fuego y coceremos unos 5 minutos removiendo, hasta que espese un poco. Apagaremos el fuego y dejaremos enfriar, pero no del todo, porque si no se queda dura. Cuando esté templada, pero algo firme, rellenaremos las galletas poniendo una cucharadita en el centro de una sin agujero y cubriendo con una que tenga el hueco para que se vea.
            </pas>
            <pas>
                Guardar: La mermelada en contacto con las galletas hace que si pasan muchas horas hasta su consumo, al aportarles humedad, estas se reblandecen y ya no están crujientes. Por lo que si vas a preparar rellenas, es mejor prepararlas un rato antes de consumirlas, o no rellenarlas, guardarlas en un recipiente hermético, cuando estén frías y preparar el relleno un rato antes de servirlas.
            </pas>
        </passos>
    </recepta>
    <recepta>
        <autor>
            <nom_persona>Chef Paco</nom_persona>
            <dni>91727431W</dni>
        </autor>
        <nom_recepta>Mijo cremoso con lentejas y sabores del bosque</nom_recepta>
        <ingredients>
            <ingredient>
                <quantitat>
                    <valor>2</valor>
                    <mesura>cucharadas</mesura>
                </quantitat>
                <nom>Aceite de oliva virgen extra</nom>
            </ingredient>
            <ingredient>
                <quantitat>
                    <valor>1</valor>
                    <mesura>unidad</mesura>
                </quantitat>
                <nom>Cebolla grande</nom>
            </ingredient>
            <ingredient>
                <quantitat>
                    <valor>2</valor>
                    <mesura>dientes</mesura>
                </quantitat>
                <nom>Ajo</nom>
            </ingredient>
            <ingredient>
                <quantitat>
                    <valor>300</valor>
                    <mesura>g</mesura>
                </quantitat>
                <nom>Boniato pelado</nom>
            </ingredient>
            <ingredient>
                <quantitat>
                    <valor>300</valor>
                    <mesura>g</mesura>
                </quantitat>
                <nom>Coliflor (parte blanca, sin el tronco)</nom>
            </ingredient>
            <ingredient>
                <quantitat>
                    <valor>500</valor>
                    <mesura>ml</mesura>
                </quantitat>
                <nom>Agua</nom>
            </ingredient>
            <ingredient>
                <quantitat>
                    <valor>0.5</valor>
                    <mesura>taza</mesura>
                </quantitat>
                <nom>Mijo</nom>
            </ingredient>
            <ingredient>
                <quantitat>
                    <valor>0.5</valor>
                    <mesura>taza</mesura>
                </quantitat>
                <nom>Lentejas rojas partidas</nom>
            </ingredient>
            <ingredient>
                <quantitat>
                    <valor>1</valor>
                    <mesura>cucharadita</mesura>
                </quantitat>
                <nom>Sal</nom>
